### PR TITLE
feat(duckdb): Add transpilation support for COLLATE function

### PR DESCRIPTION
**Pull request by fivetran-amrutabhimsenayachit**
DuckDB requires collation names to be unquoted identifiers `(e.g., COLLATE NOCASE)`, not quoted string literals (e.g., `COLLATE 'en'`)
SQLGlot preserves the Snowflake quoted collation string as-is; DuckDB's parser rejects any quoted collation name with a syntax error.

```
SF:
SELECT 'hello' COLLATE '' AS empty_string, 'hello' COLLATE 'en' AS locale, 'hello' COLLATE 'en-cs' AS locale_cs, 'hello' COLLATE 'en-as' AS locale_as, 'hello' COLLATE 'en-ps' AS locale_ps"
+-----------------------------------------------------------+
| EMPTY_STRING | LOCALE | LOCALE_CS | LOCALE_AS | LOCALE_PS |
|--------------+--------+-----------+-----------+-----------|
| hello        | hello  | hello     | hello     | hello     |
+-----------------------------------------------------------+

Trnaspilation:
 python3 -c "import sqlglot; print(sqlglot.transpile(\"SELECT 'hello' COLLATE '' AS empty_string, 'hello' COLLATE 'en' AS locale, 'hello' COLLATE 'en-cs' AS locale_cs, 'hello' COLLATE 'en-as' AS locale_as, 'hello' COLLATE 'en-ps' AS locale_ps\", read='snowflake', write='duckdb')[0])"
SELECT 'hello' AS empty_string, 'hello' COLLATE en AS locale, 'hello' COLLATE en AS locale_cs, 'hello' COLLATE en AS locale_as, 'hello' COLLATE en AS locale_ps

DDB:
│ empty_string │ locale  │ locale_cs │ locale_as │ locale_ps │
│   varchar    │ varchar │  varchar  │  varchar  │  varchar  │
├──────────────┼─────────┼───────────┼───────────┼───────────┤
│ hello        │ hello   │ hello     │ hello     │ hello     │
└──────────────┴─────────┴───────────┴───────────┴───────────┘


Unsupported cases:
 python3 -c "
from sqlglot import transpile
from sqlglot.errors import UnsupportedError, ErrorLevel
for spec in ['ci', 'ai', 'upper', 'lower', 'utf8', 'bin']:
    try:
        transpile(f\"SELECT 'hello' COLLATE '{spec}'\", read='snowflake', write='duckdb', unsupported_level=ErrorLevel.RAISE)
    except UnsupportedError as e:
        print(f\"'{spec}' -> UnsupportedError: {e}\")
"
'ci' -> UnsupportedError: Snowflake collation specifier 'ci' has no DuckDB equivalent
'ai' -> UnsupportedError: Snowflake collation specifier 'ai' has no DuckDB equivalent
'upper' -> UnsupportedError: Snowflake collation specifier 'upper' has no DuckDB equivalent
'lower' -> UnsupportedError: Snowflake collation specifier 'lower' has no DuckDB equivalent
'utf8' -> UnsupportedError: Snowflake collation specifier 'utf8' has no DuckDB equivalent
'bin' -> UnsupportedError: Snowflake collation specifier 'bin' has no DuckDB equivalent
```

### CODE REVIEW

File: sqlglot/generators/duckdb.py [hunk 1]
```diff
@@ -2997,6 +2997,12 @@ def collation_sql(self, expression: exp.Collation) -> str:
         self.unsupported("COLLATION function is not supported by DuckDB")
         return self.function_fallback_sql(expression)
 
+    def collate_sql(self, expression: exp.Collate) -> str:
+        return self.binary(
+            exp.Collate(this=expression.this, expression=exp.Var(this=expression.expression.name)),
+            "COLLATE",
+        )
```
Comment (georgesittas) [inline sqlglot/generators/duckdb.py]: This isn't right, it breaks roundtrip in DuckDB for nested collation applications:

```
(sqlglot) ➜  sqlglot git:(RD-1147699-collate) ✗ sqlglot --read duckdb "SELECT 'hello' COLLATE NOCASE.NOACCENT = 'hElLÖ'"
SELECT 'hello' COLLATE NOACCENT = 'hElLÖ'
```

Check out https://duckdb.org/docs/current/sql/expressions/collations.

We should instead check if `expression.expression.is_string` and in that case do a best-effort transpilation by replacing `expression.expression` with an `exp.var(...)` equivalent. Then, use the superclass' generator to handle the rest.

Note that this time, checking for `is_string` is not bad practice, because Snowflake's grammar does not allow columns to be injected into `COLLATE`:

```
(sqlglot) ➜  sqlglot git:(RD-1147699-collate) ✗ runsf "WITH t AS (SELECT 'en-ci' AS x) SELECT 'foo' COLLATE x FROM t"
WITH t AS (SELECT 'en-ci' AS x) SELECT 'foo' COLLATE x FROM t
╭─ Error ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 001003 (42000): 01c38804-0008-f5fd-0001-b9fe0879c546: SQL compilation error:                                                                                                            │
│ syntax error line 1 at position 53 unexpected 'x'.                                                                                                                                      │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

Note that more work will be needed to handle Snowflake's `COLLATE` properly in DuckDB. For example, Snowflake combines collations using `-`, such as:

```
(sqlglot) ➜  sqlglot git:(RD-1147699-collate) ✗ runsf "SELECT 'foo' COLLATE 'en-ci'"
SELECT 'foo' COLLATE 'en-ci'
+-----------------------+
| 'FOO' COLLATE 'EN-CI' |
|-----------------------|
| foo                   |
+-----------------------+
```

However, DuckDB combines them using `.`, see example above. Additionally, some specifiers in Snowflake are named differently than the DuckDB equivalents (e.g. `CI` vs `NOCASE`), and there may also be specifiers not supported in DuckDB at all. You'll need to refer to [this](https://docs.snowflake.com/en/sql-reference/collation#supported-specifiers) page to get a better sense.

File: sqlglot/generators/duckdb.py [hunk 2]
```diff
@@ -2998,9 +3013,44 @@ def collation_sql(self, expression: exp.Collation) -> str:
...
-        return self.binary(
-            exp.Collate(this=expression.this, expression=exp.Var(this=expression.expression.name)),
-            "COLLATE",
+        if not expression.expression.is_string:
+            return super().collate_sql(expression)
+
+        raw = expression.expression.name
+        if not raw:
+            return self.sql(expression.this)
+
```
Comment (georgesittas) [inline sqlglot/generators/duckdb.py:3014]:
```suggestion
```

File: sqlglot/generators/duckdb.py [hunk 3]
```diff
@@ -2998,9 +3013,44 @@ def collation_sql(self, expression: exp.Collation) -> str:
...
+                            f"Snowflake '{lower}' controls sort order (uppercase-first vs "
+                            "lowercase-first); DuckDB NOCASE only affects equality, not ordering direction"
+                        )
+                    duckdb_parts.append(mapped)
+            elif lower in _SNOWFLAKE_COLLATION_UNSUPPORTED:
+                self.unsupported(f"Snowflake collation specifier '{part}' has no DuckDB equivalent")
+            else:
+                self.unsupported(
+                    f"Snowflake locale collation '{part}' requires the ICU extension in DuckDB"
+                )
```
Comment (georgesittas) [inline sqlglot/generators/duckdb.py]: We don't need to report this here. If the user has the ICU extension it'll just be noise. If they don't, the transpiled query will fail and they will know anyway.

```suggestion
```

File: sqlglot/generators/duckdb.py [hunk 4]
```diff
@@ -2998,9 +3013,44 @@ def collation_sql(self, expression: exp.Collation) -> str:
...
+                duckdb_parts.append(lower)
+
+        if not duckdb_parts:
+            return self.sql(expression.this)
+
```
Comment (georgesittas) [inline sqlglot/generators/duckdb.py]: Let's add every part to `duckdb_parts`, regardless of it being supported. Then, you won't need this branch as a special case, but at the same time you'll have warned about any part(s) being unsupported.

File: sqlglot/generators/duckdb.py [hunk 5]
```diff
@@ -82,6 +82,21 @@
 
 MAX_BIT_POSITION = exp.Literal.number(32768)
 
+# Mapping of Snowflake collation specifiers to DuckDB equivalents.
+# None = silent drop (Snowflake default — DuckDB already behaves the same way).
+_SNOWFLAKE_COLLATION_MAP: dict[str, str | None] = {
+    "ci": "NOCASE",
+    "ai": "NOACCENT",
+    "utf8": "BINARY",
+    "bin": "BINARY",
```
Comment (georgesittas) [inline sqlglot/generators/duckdb.py]: @fivetran-amrutabhimsenayachit there's no `BINARY` collation in DuckDB:

```
(sqlglot) ➜  sqlglot git:(main) ✗ runddb "SELECT 'SS' COLLATE BINARY"
Parser Error:
syntax error at or near "BINARY"

LINE 1: SELECT 'SS' COLLATE BINARY
                            ^
```

This is weird, given the docs say:

> By default, the `BINARY` collation is used.

Mapping these to `None` iss also not always correct, because `COLLATE 'utf8'` in Snowflake can override a column-level collation to force binary comparison. For example:

```sql
-- Snowflake
CREATE TABLE t (val VARCHAR COLLATE 'en-ci');
INSERT INTO t VALUES ('hello'), ('HELLO'), ('Hello');

SELECT val, val COLLATE 'utf8' = 'hello' AS binary_cmp FROM t;
-- hello  => TRUE
-- HELLO  => FALSE   (utf8 overrides the column's en-ci collation)
-- Hello  => FALSE

-- DuckDB (if we drop the COLLATE entirely)
CREATE TABLE t (val VARCHAR COLLATE NOCASE);
INSERT INTO t VALUES ('hello'), ('HELLO'), ('Hello');

SELECT val, val = 'hello' AS no_collate_cmp FROM t;
-- hello  => TRUE
-- HELLO  => TRUE    (NOCASE from the column definition still applies)
-- Hello  => TRUE
```

I think we should treat these two as unsupported too.

File: sqlglot/generators/duckdb.py [hunk 6]
```diff
@@ -82,6 +82,21 @@
 
 MAX_BIT_POSITION = exp.Literal.number(32768)
 
+# Mapping of Snowflake collation specifiers to DuckDB equivalents.
+# None = silent drop (Snowflake default — DuckDB already behaves the same way).
+_SNOWFLAKE_COLLATION_MAP: dict[str, str | None] = {
+    "ci": "NOCASE",
+    "ai": "NOACCENT",
```
Comment (georgesittas) [inline sqlglot/generators/duckdb.py]: I'm worried about transpiling these as-is, despite the `unsupported` call. For example:

```sql
-- Snowflake produces FALSE, TRUE
SELECT 'i' COLLATE 'tr-ci' = 'I' COLLATE 'tr-ci', 'ς' COLLATE 'en-ci' = 'Σ' COLLATE 'en-ci'

-- DuckDB produces TRUE, FALSE
SELECT 'i' COLLATE NOCASE  = 'I' COLLATE NOCASE, 'ς' COLLATE NOCASE  = 'Σ' COLLATE NOCASE
```

File: sqlglot/generators/duckdb.py [hunk 7]
```diff
@@ -82,6 +82,21 @@
...
+    "utf8": "BINARY",
+    "bin": "BINARY",
+    "upper": "NOCASE",
+    "lower": "NOCASE",
```
Comment (georgesittas) [inline sqlglot/generators/duckdb.py]: These as well, I'm not sure if we should transpile them like this given these discrepancies:

```sql
-- Snowflake returns TRUE, FALSE, TRUE
SELECT 'ß' COLLATE 'en-upper' = 'SS' COLLATE 'en-upper', 'σ' COLLATE 'en-lower' = 'ς' COLLATE 'en-lower', 'σ' COLLATE 'en-upper' = 'ς' COLLATE 'en-upper'

-- DuckDB returns FALSE, FALSE
SELECT 'ß' COLLATE NOCASE = 'SS' COLLATE NOCASE, SELECT 'σ' COLLATE NOCASE = 'ς' COLLATE NOCASE
```

This shows that `'lower'` and `'upper'` are semantically distinct in Snowflake, but both are mapped to the same `NOCASE` in DuckDB.

File: sqlglot/generators/duckdb.py (hunk 5 above)
Comment (fivetran-amrutabhimsenayachit) [reply sqlglot/generators/duckdb.py]: Makes sense. I applied it only for `cs/as` and missed it for `utf8/bin`.

File: sqlglot/generators/duckdb.py [hunk 8]
```diff
@@ -82,6 +82,13 @@
 
 MAX_BIT_POSITION = exp.Literal.number(32768)
 
+# cs/as/ps are Snowflake defaults; DuckDB already behaves the same way, so they are safe to drop.
+# Note: "as" is also a reserved keyword in DuckDB, making it impossible to pass through.
+_SNOWFLAKE_COLLATION_DEFAULTS = frozenset({"cs", "as", "ps"})
+_SNOWFLAKE_COLLATION_UNSUPPORTED = frozenset(
+    {"ci", "ai", "upper", "lower", "utf8", "bin", "pi", "fl", "fu", "trim", "ltrim", "rtrim"}
+)
```
Comment (georgesittas) [inline sqlglot/generators/duckdb.py:90]: Why are we tracking both supported and unsupported specifiers? The `cs`, `as`, `ps` should be enough, since, if there's _any_ other specifier besides them, we just call `unsupported`.

Comment (georgesittas) [reply sqlglot/generators/duckdb.py:90]: Nvm, this makes sense, the extension specifiers _are_ supported after all in duckdb.
