### ISSUE TITLE
Parsing of invalid alias tokens fails with sqlglot 20.9+

### ISSUE THREAD

**Issue by mpf82** [tobymao/sqlglot#2895]
Code to reproduce:

```python
import sqlglot

def check_syntax( sql: str ):
    dia = sqlglot.Dialect()
    parser: sqlglot.Parser = dia.parser( error_level="CUSTOM" )
    errors = []
    try:
        tokens = dia.tokenizer.tokenize( sql )
    except Exception as e:
        tokens     = dia.tokenizer.tokens
        parser.sql = sql    # pylint: disable=assigning-non-slot
        parser.raise_error( str( e ), tokens[ -1 ] if tokens else None )
        errors += [ ee for pe in parser.errors for ee in pe.errors ]

    # print(tokens) # output see below
    e = parser.parse( tokens, sql )
    errors += [ ee for pe in parser.errors for ee in pe.errors ]
    return errors

syntax_errors = check_syntax( "as as" )
print(syntax_errors)
```

Prior to version 20.9, ``print(syntax_errors)`` would output

> [{'description': "Required keyword: 'this' missing for <class 'sqlglot.expressions.Alias'>", 'line': 1, 'col': 5, 'start_context': 'as ', 'highlight': 'as', 'end_context': '', 'into_expression': None}]

But after upgrading to 20.9 (also tested with 20.10) this will raise an AttributeError in ``e = parser.parse( tokens, sql )``:

```python
#   File "C:\Python311\Lib\site-packages\sqlglot\parser.py", line 3372, in _parse_expression
#     return self._parse_alias(self._parse_conjunction())
#            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "C:\Python311\Lib\site-packages\sqlglot\parser.py", line 4979, in _parse_alias
#     if not this.comments and this.this.comments:
#                              ^^^^^^^^^^^^^^^^^^
# AttributeError: 'NoneType' object has no attribute 'comments'
```

The output of ``print(tokens)`` is:
> [<Token token_type: TokenType.ALIAS, text: as, line: 1, col: 2, start: 0, end: 1, comments: []>, <Token token_type: TokenType.ALIAS, text: as, line: 1, col: 5, start: 3, end: 4, comments: []>]

executing ``sqlglot.parse("as as ")`` will output the follwoing for 20.0 - 20.10, so this is consistent, only the parsing of the tokens fails.
> sqlglot.errors.ParseError: Required keyword: 'this' missing for <class 'sqlglot.expressions.Alias'>. Line 1, Col: 5.

Motivation of this code: I am attempting to get as much details on parse / syntax errors on a given user sql as possible, but getting these error details from sqlglot directly was not possible, thus the code attempts to tokenize the statement as far as possible and then it tries to parse the tokens up to the point where the tokenizing failed, collecting more possible errors.

I think the problem is the assumption of a comment in ``_parse_alias`` in parser.py, as pointed out by the stack trace, that was added in sqlglot 20.9:

```python
            # Moves the comment next to the alias in `expr /* comment */ AS alias`
            if not this.comments and this.this.comments:
                this.comments = this.this.comments
                this.this.comments = None
```

I am not saying that ``as as`` (as tokens) should be parseable, but throwing an unhandled AttributeErro should be avoided.
